([rule1] of defeasible-rule
   (rule-name rule1)
   (original-rule "rule1 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_direktni\" ) ) => ( crime_art143 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art143)
   (negated no)
   (superior)
   (deductive-rule rule1-deductive)
   (overruled-rule rule1-overruled)
   (system no)
   (support-rule rule1-support)
   (defeasibly-rule rule1-defeasibly)
   (defeated-rule nil))

([rule2] of defeasible-rule
   (rule-name rule2)
   (original-rule "rule2 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_eventualni\" ) ) => ( crime_art143 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art143)
   (negated no)
   (superior)
   (deductive-rule rule2-deductive)
   (overruled-rule rule2-overruled)
   (system no)
   (support-rule rule2-support)
   (defeasibly-rule rule2-defeasibly)
   (defeated-rule nil))

([rule4] of defeasible-rule
   (rule-name rule4)
   (original-rule "rule4 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"svirep\" ) ) => ( crime_art144_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_1)
   (negated no)
   (superior)
   (deductive-rule rule4-deductive)
   (overruled-rule rule4-overruled)
   (system no)
   (support-rule rule4-support)
   (defeasibly-rule rule4-defeasibly)
   (defeated-rule nil))

([rule5] of defeasible-rule
   (rule-name rule5)
   (original-rule "rule5 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"podmukao\" ) ) => ( crime_art144_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_1)
   (negated no)
   (superior)
   (deductive-rule rule5-deductive)
   (overruled-rule rule5-overruled)
   (system no)
   (support-rule rule5-support)
   (defeasibly-rule rule5-defeasibly)
   (defeated-rule nil))

([rule6] of defeasible-rule
   (rule-name rule6)
   (original-rule "rule6 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"bezobzirno_nasilnicko_ponasanje\" ) ) => ( crime_art144_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_2)
   (negated no)
   (superior)
   (deductive-rule rule6-deductive)
   (overruled-rule rule6-overruled)
   (system no)
   (support-rule rule6-support)
   (defeasibly-rule rule6-defeasibly)
   (defeated-rule nil))

([rule7] of defeasible-rule
   (rule-name rule7)
   (original-rule "rule7 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_direktni\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_third_parties \"true\" ) ) => ( crime_art144_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_3)
   (negated no)
   (superior)
   (deductive-rule rule7-deductive)
   (overruled-rule rule7-overruled)
   (system no)
   (support-rule rule7-support)
   (defeasibly-rule rule7-defeasibly)
   (defeated-rule nil))

([rule7b] of defeasible-rule
   (rule-name rule7b)
   (original-rule "rule7b ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_eventualni\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_third_parties \"true\" ) ) => ( crime_art144_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_3)
   (negated no)
   (superior)
   (deductive-rule rule7b-deductive)
   (overruled-rule rule7b-overruled)
   (system no)
   (support-rule rule7b-support)
   (defeasibly-rule rule7b-defeasibly)
   (defeated-rule nil))

([rule8] of defeasible-rule
   (rule-name rule8)
   (original-rule "rule8 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_motive \"koristoljublje\" ) ) => ( crime_art144_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_4)
   (negated no)
   (superior)
   (deductive-rule rule8-deductive)
   (overruled-rule rule8-overruled)
   (system no)
   (support-rule rule8-support)
   (defeasibly-rule rule8-defeasibly)
   (defeated-rule nil))

([rule9] of defeasible-rule
   (rule-name rule9)
   (original-rule "rule9 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_motive \"izvrsenje_ili_prikrivanje_drugog_krivicnog_djela\" ) ) => ( crime_art144_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_4)
   (negated no)
   (superior)
   (deductive-rule rule9-deductive)
   (overruled-rule rule9-overruled)
   (system no)
   (support-rule rule9-support)
   (defeasibly-rule rule9-defeasibly)
   (defeated-rule nil))

([rule9b] of defeasible-rule
   (rule-name rule9b)
   (original-rule "rule9b ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_motive \"niske_pobude\" ) ) => ( crime_art144_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_4)
   (negated no)
   (superior)
   (deductive-rule rule9b-deductive)
   (overruled-rule rule9b-overruled)
   (system no)
   (support-rule rule9b-support)
   (defeasibly-rule rule9b-defeasibly)
   (defeated-rule nil))

([rule10] of defeasible-rule
   (rule-name rule10)
   (original-rule "rule10 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_motive \"bezobzirna_osveta\" ) ) => ( crime_art144_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_4)
   (negated no)
   (superior)
   (deductive-rule rule10-deductive)
   (overruled-rule rule10-overruled)
   (system no)
   (support-rule rule10-support)
   (defeasibly-rule rule10-defeasibly)
   (defeated-rule nil))

([rule11] of defeasible-rule
   (rule-name rule11)
   (original-rule "rule11 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"sluzbeno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:duty_connection \"u_vrsenju_sluzbene_duznosti\" ) ) => ( crime_art144_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_5)
   (negated no)
   (superior)
   (deductive-rule rule11-deductive)
   (overruled-rule rule11-overruled)
   (system no)
   (support-rule rule11-support)
   (defeasibly-rule rule11-defeasibly)
   (defeated-rule nil))

([rule12] of defeasible-rule
   (rule-name rule12)
   (original-rule "rule12 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"vojno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:duty_connection \"u_vrsenju_sluzbene_duznosti\" ) ) => ( crime_art144_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_5)
   (negated no)
   (superior)
   (deductive-rule rule12-deductive)
   (overruled-rule rule12-overruled)
   (system no)
   (support-rule rule12-support)
   (defeasibly-rule rule12-defeasibly)
   (defeated-rule nil))

([rule13] of defeasible-rule
   (rule-name rule13)
   (original-rule "rule13 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) => ( crime_art144_6 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_6)
   (negated no)
   (superior)
   (deductive-rule rule13-deductive)
   (overruled-rule rule13-overruled)
   (system no)
   (support-rule rule13-support)
   (defeasibly-rule rule13-defeasibly)
   (defeated-rule nil))

([rule14] of defeasible-rule
   (rule-name rule14)
   (original-rule "rule14 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"bremenita_zena\" ) ) => ( crime_art144_6 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_6)
   (negated no)
   (superior)
   (deductive-rule rule14-deductive)
   (overruled-rule rule14-overruled)
   (system no)
   (support-rule rule14-support)
   (defeasibly-rule rule14-defeasibly)
   (defeated-rule nil))

([rule15] of defeasible-rule
   (rule-name rule15)
   (original-rule "rule15 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"clan_porodice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_previously_abused \"true\" ) ) => ( crime_art144_7 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_7)
   (negated no)
   (superior)
   (deductive-rule rule15-deductive)
   (overruled-rule rule15-overruled)
   (system no)
   (support-rule rule15-support)
   (defeasibly-rule rule15-defeasibly)
   (defeated-rule nil))

([rule16] of defeasible-rule
   (rule-name rule16)
   (original-rule "rule16 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_count \"vise\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_direktni\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_eventualni\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"na_mah\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_psych_state \"porodjajni_poremecaj\" ) ) ) ( not ( and ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"punoljetno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_health_state \"tesko_zdravstveno_stanje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_explicit_request \"da\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_motive \"samilost\" ) ) ) ) => ( crime_art144_8 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144_8)
   (negated no)
   (superior)
   (deductive-rule rule16-deductive)
   (overruled-rule rule16-overruled)
   (system no)
   (support-rule rule16-support)
   (defeasibly-rule rule16-defeasibly)
   (defeated-rule nil))

([rule17] of defeasible-rule
   (rule-name rule17)
   (original-rule "rule17 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"na_mah\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"napad_od_ubijenog\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"bez_krivice_ucinioca\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_intensity_distress \"true\" ) ) => ( crime_art145 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art145)
   (negated no)
   (superior)
   (deductive-rule rule17-deductive)
   (overruled-rule rule17-overruled)
   (system no)
   (support-rule rule17-support)
   (defeasibly-rule rule17-defeasibly)
   (defeated-rule nil))

([rule18] of defeasible-rule
   (rule-name rule18)
   (original-rule "rule18 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"na_mah\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"zlostavljanje_od_ubijenog\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"bez_krivice_ucinioca\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_intensity_distress \"true\" ) ) => ( crime_art145 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art145)
   (negated no)
   (superior)
   (deductive-rule rule18-deductive)
   (overruled-rule rule18-overruled)
   (system no)
   (support-rule rule18-support)
   (defeasibly-rule rule18-defeasibly)
   (defeated-rule nil))

([rule18b] of defeasible-rule
   (rule-name rule18b)
   (original-rule "rule18b ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"na_mah\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"tesko_vrijedjanje_od_ubijenog\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"bez_krivice_ucinioca\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_intensity_distress \"true\" ) ) => ( crime_art145 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art145)
   (negated no)
   (superior)
   (deductive-rule rule18b-deductive)
   (overruled-rule rule18b-overruled)
   (system no)
   (support-rule rule18b-support)
   (defeasibly-rule rule18b-defeasibly)
   (defeated-rule nil))

([rule19] of defeasible-rule
   (rule-name rule19)
   (original-rule "rule19 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_psych_state \"porodjajni_poremecaj\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_is_mother \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) => ( crime_art146 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art146)
   (negated no)
   (superior)
   (deductive-rule rule19-deductive)
   (overruled-rule rule19-overruled)
   (system no)
   (support-rule rule19-support)
   (defeasibly-rule rule19-defeasibly)
   (defeated-rule nil))

([rule21] of defeasible-rule
   (rule-name rule21)
   (original-rule "rule21 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"punoljetno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_health_state \"tesko_zdravstveno_stanje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_explicit_request \"da\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_motive \"samilost\" ) ) => ( crime_art147 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art147)
   (negated no)
   (superior)
   (deductive-rule rule21-deductive)
   (overruled-rule rule21-overruled)
   (system no)
   (support-rule rule21-support)
   (defeasibly-rule rule21-defeasibly)
   (defeated-rule nil))

([rule22] of defeasible-rule
   (rule-name rule22)
   (original-rule "rule22 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"nehat\" ) ) => ( crime_art148 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art148)
   (negated no)
   (superior)
   (deductive-rule rule22-deductive)
   (overruled-rule rule22-overruled)
   (system no)
   (support-rule rule22-support)
   (defeasibly-rule rule22-defeasibly)
   (defeated-rule nil))

([rule24] of defeasible-rule
   (rule-name rule24)
   (original-rule "rule24 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetnik\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"bitno_smanjena_uracunljivost\" ) ) ) => ( crime_art149_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_1)
   (negated no)
   (superior)
   (deductive-rule rule24-deductive)
   (overruled-rule rule24-overruled)
   (system no)
   (support-rule rule24-support)
   (defeasibly-rule rule24-defeasibly)
   (defeated-rule nil))

([rule25] of defeasible-rule
   (rule-name rule25)
   (original-rule "rule25 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetnik\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"bitno_smanjena_uracunljivost\" ) ) ) => ( crime_art149_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_1)
   (negated no)
   (superior)
   (deductive-rule rule25-deductive)
   (overruled-rule rule25-overruled)
   (system no)
   (support-rule rule25-support)
   (defeasibly-rule rule25-defeasibly)
   (defeated-rule nil))

([rule26] of defeasible-rule
   (rule-name rule26)
   (original-rule "rule26 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"punoljetno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_health_state \"tesko_zdravstveno_stanje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_explicit_request \"da\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) => ( crime_art149_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_2)
   (negated no)
   (superior)
   (deductive-rule rule26-deductive)
   (overruled-rule rule26-overruled)
   (system no)
   (support-rule rule26-support)
   (defeasibly-rule rule26-defeasibly)
   (defeated-rule nil))

([rule27] of defeasible-rule
   (rule-name rule27)
   (original-rule "rule27 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"punoljetno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_health_state \"tesko_zdravstveno_stanje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_explicit_request \"da\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) => ( crime_art149_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_2)
   (negated no)
   (superior)
   (deductive-rule rule27-deductive)
   (overruled-rule rule27-overruled)
   (system no)
   (support-rule rule27-support)
   (defeasibly-rule rule27-defeasibly)
   (defeated-rule nil))

([rule29b] of defeasible-rule
   (rule-name rule29b)
   (original-rule "rule29b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"bitno_smanjena_uracunljivost\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_3)
   (negated no)
   (superior)
   (deductive-rule rule29b-deductive)
   (overruled-rule rule29b-overruled)
   (system no)
   (support-rule rule29b-support)
   (defeasibly-rule rule29b-defeasibly)
   (defeated-rule nil))

([rule28] of defeasible-rule
   (rule-name rule28)
   (original-rule "rule28 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetnik\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_3)
   (negated no)
   (superior)
   (deductive-rule rule28-deductive)
   (overruled-rule rule28-overruled)
   (system no)
   (support-rule rule28-support)
   (defeasibly-rule rule28-defeasibly)
   (defeated-rule nil))

([rule28b] of defeasible-rule
   (rule-name rule28b)
   (original-rule "rule28b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetnik\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_3)
   (negated no)
   (superior)
   (deductive-rule rule28b-deductive)
   (overruled-rule rule28b-overruled)
   (system no)
   (support-rule rule28b-support)
   (defeasibly-rule rule28b-defeasibly)
   (defeated-rule nil))

([rule29] of defeasible-rule
   (rule-name rule29)
   (original-rule "rule29 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"bitno_smanjena_uracunljivost\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_3)
   (negated no)
   (superior)
   (deductive-rule rule29-deductive)
   (overruled-rule rule29-overruled)
   (system no)
   (support-rule rule29-support)
   (defeasibly-rule rule29-defeasibly)
   (defeated-rule nil))

([rule30] of defeasible-rule
   (rule-name rule30)
   (original-rule "rule30 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_4)
   (negated no)
   (superior)
   (deductive-rule rule30-deductive)
   (overruled-rule rule30-overruled)
   (system no)
   (support-rule rule30-support)
   (defeasibly-rule rule30-defeasibly)
   (defeated-rule nil))

([rule30b] of defeasible-rule
   (rule-name rule30b)
   (original-rule "rule30b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule30b-deductive)
   (overruled-rule rule30b-overruled)
   (system no)
   (support-rule rule30b-support)
   (defeasibly-rule rule30b-defeasibly)
   (defeated-rule nil))

([rule31] of defeasible-rule
   (rule-name rule31)
   (original-rule "rule31 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_4)
   (negated no)
   (superior)
   (deductive-rule rule31-deductive)
   (overruled-rule rule31-overruled)
   (system no)
   (support-rule rule31-support)
   (defeasibly-rule rule31-defeasibly)
   (defeated-rule nil))

([rule31b] of defeasible-rule
   (rule-name rule31b)
   (original-rule "rule31b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule31b-deductive)
   (overruled-rule rule31b-overruled)
   (system no)
   (support-rule rule31b-support)
   (defeasibly-rule rule31b-defeasibly)
   (defeated-rule nil))

([rule32] of defeasible-rule
   (rule-name rule32)
   (original-rule "rule32 ( lc:case ( lc:defendant ?Defendant ) ( lc:inhuman_treatment \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_subordination \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"nehat\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:death_attributed_to_negligence \"da\" ) ) ) => ( crime_art149_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_5)
   (negated no)
   (superior)
   (deductive-rule rule32-deductive)
   (overruled-rule rule32-overruled)
   (system no)
   (support-rule rule32-support)
   (defeasibly-rule rule32-defeasibly)
   (defeated-rule nil))

([rule33] of defeasible-rule
   (rule-name rule33)
   (original-rule "rule33 ( lc:case ( lc:defendant ?Defendant ) ( lc:inhuman_treatment \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_subordination \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"nehat\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:death_attributed_to_negligence \"da\" ) ) ) => ( crime_art149_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_5)
   (negated no)
   (superior)
   (deductive-rule rule33-deductive)
   (overruled-rule rule33-overruled)
   (system no)
   (support-rule rule33-support)
   (defeasibly-rule rule33-defeasibly)
   (defeated-rule nil))

([rule34] of defeasible-rule
   (rule-name rule34)
   (original-rule "rule34 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"pristanak\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_action_mode \"izvrsi_pobacaj\" ) ) => ( crime_art150_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150_1)
   (negated no)
   (superior)
   (deductive-rule rule34-deductive)
   (overruled-rule rule34-overruled)
   (system no)
   (support-rule rule34-support)
   (defeasibly-rule rule34-defeasibly)
   (defeated-rule nil))

([rule34b] of defeasible-rule
   (rule-name rule34b)
   (original-rule "rule34b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"pristanak\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_action_mode \"pomogne_izvrsenje_pobacaja\" ) ) => ( crime_art150_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150_1)
   (negated no)
   (superior)
   (deductive-rule rule34b-deductive)
   (overruled-rule rule34b-overruled)
   (system no)
   (support-rule rule34b-support)
   (defeasibly-rule rule34b-defeasibly)
   (defeated-rule nil))

([rule36b] of defeasible-rule
   (rule-name rule36b)
   (original-rule "rule36b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"bez_pristanka\" ) ) => ( crime_art150_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150_2)
   (negated no)
   (superior)
   (deductive-rule rule36b-deductive)
   (overruled-rule rule36b-overruled)
   (system no)
   (support-rule rule36b-support)
   (defeasibly-rule rule36b-defeasibly)
   (defeated-rule nil))

([rule37] of defeasible-rule
   (rule-name rule37)
   (original-rule "rule37 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetna_trudnica\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"bez_pristanka\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guardian_consent \"ne\" ) ) ) => ( crime_art150_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150_2)
   (negated no)
   (superior)
   (deductive-rule rule37-deductive)
   (overruled-rule rule37-overruled)
   (system no)
   (support-rule rule37-support)
   (defeasibly-rule rule37-defeasibly)
   (defeated-rule nil))

([rule38b] of defeasible-rule
   (rule-name rule38b)
   (original-rule "rule38b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"pristanak\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_action_mode \"izvrsi_pobacaj\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_action_mode \"pomogne_izvrsenje_pobacaja\" ) ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_outcomes \"smrt\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_is_mother \"true\" ) ) ) => ( crime_art150_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150_3)
   (negated no)
   (superior)
   (deductive-rule rule38b-deductive)
   (overruled-rule rule38b-overruled)
   (system no)
   (support-rule rule38b-support)
   (defeasibly-rule rule38b-defeasibly)
   (defeated-rule nil))

([rule39b] of defeasible-rule
   (rule-name rule39b)
   (original-rule "rule39b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"bez_pristanka\" ) ) ( and ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetna_trudnica\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guardian_consent \"ne\" ) ) ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_outcomes \"tesko_narusavanje_zdravlja\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_is_mother \"true\" ) ) ) => ( crime_art150_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150_3)
   (negated no)
   (superior)
   (deductive-rule rule39b-deductive)
   (overruled-rule rule39b-overruled)
   (system no)
   (support-rule rule39b-support)
   (defeasibly-rule rule39b-defeasibly)
   (defeated-rule nil))

([rule40b] of defeasible-rule
   (rule-name rule40b)
   (original-rule "rule40b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"bez_pristanka\" ) ) ( and ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetna_trudnica\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guardian_consent \"ne\" ) ) ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_outcomes \"teska_tjelesna_povreda\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_is_mother \"true\" ) ) ) => ( crime_art150_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150_3)
   (negated no)
   (superior)
   (deductive-rule rule40b-deductive)
   (overruled-rule rule40b-overruled)
   (system no)
   (support-rule rule40b-support)
   (defeasibly-rule rule40b-defeasibly)
   (defeated-rule nil))

([rule41] of defeasible-rule
   (rule-name rule41)
   (original-rule "rule41 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) => ( crime_art151_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_1)
   (negated no)
   (superior)
   (deductive-rule rule41-deductive)
   (overruled-rule rule41-overruled)
   (system no)
   (support-rule rule41-support)
   (defeasibly-rule rule41-defeasibly)
   (defeated-rule nil))

([rule43] of defeasible-rule
   (rule-name rule43)
   (original-rule "rule43 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"opasnost_po_zivot\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule43-deductive)
   (overruled-rule rule43-overruled)
   (system no)
   (support-rule rule43-support)
   (defeasibly-rule rule43-defeasibly)
   (defeated-rule nil))

([rule43b] of defeasible-rule
   (rule-name rule43b)
   (original-rule "rule43b ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"unistenje_dijela_tijela\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule43b-deductive)
   (overruled-rule rule43b-overruled)
   (system no)
   (support-rule rule43b-support)
   (defeasibly-rule rule43b-defeasibly)
   (defeated-rule nil))

([rule43c] of defeasible-rule
   (rule-name rule43c)
   (original-rule "rule43c ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajno_ostecenje_organa\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule43c-deductive)
   (overruled-rule rule43c-overruled)
   (system no)
   (support-rule rule43c-support)
   (defeasibly-rule rule43c-defeasibly)
   (defeated-rule nil))

([rule43d] of defeasible-rule
   (rule-name rule43d)
   (original-rule "rule43d ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajna_nesposobnost_za_rad\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule43d-deductive)
   (overruled-rule rule43d-overruled)
   (system no)
   (support-rule rule43d-support)
   (defeasibly-rule rule43d-defeasibly)
   (defeated-rule nil))

([rule43e] of defeasible-rule
   (rule-name rule43e)
   (original-rule "rule43e ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajno_naruseno_zdravlje\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule43e-deductive)
   (overruled-rule rule43e-overruled)
   (system no)
   (support-rule rule43e-support)
   (defeasibly-rule rule43e-defeasibly)
   (defeated-rule nil))

([rule43f] of defeasible-rule
   (rule-name rule43f)
   (original-rule "rule43f ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"unakazenost\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule43f-deductive)
   (overruled-rule rule43f-overruled)
   (system no)
   (support-rule rule43f-support)
   (defeasibly-rule rule43f-defeasibly)
   (defeated-rule nil))

([rule44] of defeasible-rule
   (rule-name rule44)
   (original-rule "rule44 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:death_result \"true\" ) ) => ( crime_art151_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_3)
   (negated no)
   (superior)
   (deductive-rule rule44-deductive)
   (overruled-rule rule44-overruled)
   (system no)
   (support-rule rule44-support)
   (defeasibly-rule rule44-defeasibly)
   (defeated-rule nil))

([rule45] of defeasible-rule
   (rule-name rule45)
   (original-rule "rule45 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:negligence \"true\" ) ) => ( crime_art151_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_4)
   (negated no)
   (superior)
   (deductive-rule rule45-deductive)
   (overruled-rule rule45-overruled)
   (system no)
   (support-rule rule45-support)
   (defeasibly-rule rule45-defeasibly)
   (defeated-rule nil))

([rule46] of defeasible-rule
   (rule-name rule46)
   (original-rule "rule46 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"na_mah\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"napad_od_ubijenog\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"zlostavljanje_od_ubijenog\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"tesko_vrijedjanje_od_ubijenog\" ) ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"bez_krivice_ucinioca\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_intensity_distress \"true\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"opasnost_po_zivot\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"unistenje_dijela_tijela\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajno_ostecenje_organa\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajna_nesposobnost_za_rad\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajno_naruseno_zdravlje\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"unakazenost\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:death_result \"true\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"nehat\" ) ) ) => ( crime_art151_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_5)
   (negated no)
   (superior)
   (deductive-rule rule46-deductive)
   (overruled-rule rule46-overruled)
   (system no)
   (support-rule rule46-support)
   (defeasibly-rule rule46-defeasibly)
   (defeated-rule nil))

([rule46b] of defeasible-rule
   (rule-name rule46b)
   (original-rule "rule46b ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"na_mah\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"napad_od_ubijenog\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"zlostavljanje_od_ubijenog\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"tesko_vrijedjanje_od_ubijenog\" ) ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation_types \"bez_krivice_ucinioca\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_intensity_distress \"true\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"opasnost_po_zivot\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"unistenje_dijela_tijela\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajno_ostecenje_organa\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajna_nesposobnost_za_rad\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"trajno_naruseno_zdravlje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_injury_specific_consequences \"unakazenost\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:death_result \"true\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"nehat\" ) ) ) => ( crime_art151_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_5)
   (negated no)
   (superior)
   (deductive-rule rule46b-deductive)
   (overruled-rule rule46b-overruled)
   (system no)
   (support-rule rule46b-support)
   (defeasibly-rule rule46b-defeasibly)
   (defeated-rule nil))

([rule47] of defeasible-rule
   (rule-name rule47)
   (original-rule "rule47 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"sakacenje_zenskih_genitalija\" ) ) => ( crime_art151a ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151a)
   (negated no)
   (superior)
   (deductive-rule rule47-deductive)
   (overruled-rule rule47-overruled)
   (system no)
   (support-rule rule47-support)
   (defeasibly-rule rule47-defeasibly)
   (defeated-rule nil))

([rule48] of defeasible-rule
   (rule-name rule48)
   (original-rule "rule48 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"prisilna_sterilizacija\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"bez_pristanka\" ) ) => ( crime_art151b ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151b)
   (negated no)
   (superior)
   (deductive-rule rule48-deductive)
   (overruled-rule rule48-overruled)
   (system no)
   (support-rule rule48-support)
   (defeasibly-rule rule48-defeasibly)
   (defeated-rule nil))

([rule49] of defeasible-rule
   (rule-name rule49)
   (original-rule "rule49 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"prisilna_sterilizacija\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:sterilization_goal \"onemogucavanje_reprodukcije\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_consent \"bez_pristanka\" ) ) => ( crime_art151b ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151b)
   (negated no)
   (superior)
   (deductive-rule rule49-deductive)
   (overruled-rule rule49-overruled)
   (system no)
   (support-rule rule49-support)
   (defeasibly-rule rule49-defeasibly)
   (defeated-rule nil))

([rule50] of defeasible-rule
   (rule-name rule50)
   (original-rule "rule50 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"laka tjelesna povreda\" ) ) => ( crime_art152_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_1)
   (negated no)
   (superior)
   (deductive-rule rule50-deductive)
   (overruled-rule rule50-overruled)
   (system no)
   (support-rule rule50-support)
   (defeasibly-rule rule50-defeasibly)
   (defeated-rule nil))

([rule51] of defeasible-rule
   (rule-name rule51)
   (original-rule "rule51 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"laka tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon_used \"true\" ) ) => ( crime_art152_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_2)
   (negated no)
   (superior)
   (deductive-rule rule51-deductive)
   (overruled-rule rule51-overruled)
   (system no)
   (support-rule rule51-support)
   (defeasibly-rule rule51-defeasibly)
   (defeated-rule nil))

([rule52] of defeasible-rule
   (rule-name rule52)
   (original-rule "rule52 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_means_type \"opasno_orudje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity_level \"laka\" ) ) => ( crime_art152_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_2)
   (negated no)
   (superior)
   (deductive-rule rule52-deductive)
   (overruled-rule rule52-overruled)
   (system no)
   (support-rule rule52-support)
   (defeasibly-rule rule52-defeasibly)
   (defeated-rule nil))

([rule53] of defeasible-rule
   (rule-name rule53)
   (original-rule "rule53 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_means_type \"sredstvo_podobno_za_tesku_povredu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity_level \"laka\" ) ) => ( crime_art152_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_2)
   (negated no)
   (superior)
   (deductive-rule rule53-deductive)
   (overruled-rule rule53-overruled)
   (system no)
   (support-rule rule53-support)
   (defeasibly-rule rule53-defeasibly)
   (defeated-rule nil))

([rule53b] of defeasible-rule
   (rule-name rule53b)
   (original-rule "rule53b ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"laka tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation \"true\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon_used \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_means_type \"opasno_orudje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_means_type \"sredstvo_podobno_za_tesku_povredu\" ) ) ) => ( crime_art152_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_3)
   (negated no)
   (superior)
   (deductive-rule rule53b-deductive)
   (overruled-rule rule53b-overruled)
   (system no)
   (support-rule rule53b-support)
   (defeasibly-rule rule53b-defeasibly)
   (defeated-rule nil))

([rule54] of defeasible-rule
   (rule-name rule54)
   (original-rule "rule54 ( lc:case ( lc:defendant ?Defendant ) ( lc:fight_participation \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:death_result \"true\" ) ) => ( crime_art153 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art153)
   (negated no)
   (superior)
   (deductive-rule rule54-deductive)
   (overruled-rule rule54-overruled)
   (system no)
   (support-rule rule54-support)
   (defeasibly-rule rule54-defeasibly)
   (defeated-rule nil))

([rule55] of defeasible-rule
   (rule-name rule55)
   (original-rule "rule55 ( lc:case ( lc:defendant ?Defendant ) ( lc:fight_participation \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) => ( crime_art153 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art153)
   (negated no)
   (superior)
   (deductive-rule rule55-deductive)
   (overruled-rule rule55-overruled)
   (system no)
   (support-rule rule55-support)
   (defeasibly-rule rule55-defeasibly)
   (defeated-rule nil))

([rule56] of defeasible-rule
   (rule-name rule56)
   (original-rule "rule56 ( lc:case ( lc:defendant ?Defendant ) ( lc:fight_participation \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon_used \"true\" ) ) => ( crime_art154 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art154)
   (negated no)
   (superior)
   (deductive-rule rule56-deductive)
   (overruled-rule rule56-overruled)
   (system no)
   (support-rule rule56-support)
   (defeasibly-rule rule56-defeasibly)
   (defeated-rule nil))

([rule57] of defeasible-rule
   (rule-name rule57)
   (original-rule "rule57 ( lc:case ( lc:defendant ?Defendant ) ( lc:fight_participation \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_means_type \"opasno_orudje\" ) ) => ( crime_art154 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art154)
   (negated no)
   (superior)
   (deductive-rule rule57-deductive)
   (overruled-rule rule57-overruled)
   (system no)
   (support-rule rule57-support)
   (defeasibly-rule rule57-defeasibly)
   (defeated-rule nil))

([rule57b] of defeasible-rule
   (rule-name rule57b)
   (original-rule "rule57b ( lc:case ( lc:defendant ?Defendant ) ( lc:fight_participation \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_means_type \"sredstvo_podobno_za_tesku_povredu\" ) ) => ( crime_art154 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art154)
   (negated no)
   (superior)
   (deductive-rule rule57b-deductive)
   (overruled-rule rule57b-overruled)
   (system no)
   (support-rule rule57b-support)
   (defeasibly-rule rule57b-defeasibly)
   (defeated-rule nil))

([rule58] of defeasible-rule
   (rule-name rule58)
   (original-rule "rule58 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_caused_by_offender \"true\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_life \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_health \"true\" ) ) ) => ( crime_art155_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art155_1)
   (negated no)
   (superior)
   (deductive-rule rule58-deductive)
   (overruled-rule rule58-overruled)
   (system no)
   (support-rule rule58-support)
   (defeasibly-rule rule58-defeasibly)
   (defeated-rule nil))

([rule59] of defeasible-rule
   (rule-name rule59)
   (original-rule "rule59 ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_health \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_life \"true\" ) ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_caused_by_offender \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"tesko_narusavanje_zdravlja\" ) ) => ( crime_art155_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art155_2)
   (negated no)
   (superior)
   (deductive-rule rule59-deductive)
   (overruled-rule rule59-overruled)
   (system no)
   (support-rule rule59-support)
   (defeasibly-rule rule59-defeasibly)
   (defeated-rule nil))

([rule60] of defeasible-rule
   (rule-name rule60)
   (original-rule "rule60 ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_life \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_health \"true\" ) ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_caused_by_offender \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"smrt\" ) ) => ( crime_art155_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art155_3)
   (negated no)
   (superior)
   (deductive-rule rule60-deductive)
   (overruled-rule rule60-overruled)
   (system no)
   (support-rule rule60-support)
   (defeasibly-rule rule60-defeasibly)
   (defeated-rule nil))

([rule61] of defeasible-rule
   (rule-name rule61)
   (original-rule "rule61 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"povjereno_nemocno_lice\" ) ) => ( crime_art156 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156)
   (negated no)
   (superior)
   (deductive-rule rule61-deductive)
   (overruled-rule rule61-overruled)
   (system no)
   (support-rule rule61-support)
   (defeasibly-rule rule61-defeasibly)
   (defeated-rule nil))

([rule62] of defeasible-rule
   (rule-name rule62)
   (original-rule "rule62 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"duznost_staranja\" ) ) => ( crime_art156 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156)
   (negated no)
   (superior)
   (deductive-rule rule62-deductive)
   (overruled-rule rule62-overruled)
   (system no)
   (support-rule rule62-support)
   (defeasibly-rule rule62-defeasibly)
   (defeated-rule nil))

([rule63] of defeasible-rule
   (rule-name rule63)
   (original-rule "rule63 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"povjereno_nemocno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"teska_tjelesna_povreda\" ) ) => ( crime_art156_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156_2)
   (negated no)
   (superior)
   (deductive-rule rule63-deductive)
   (overruled-rule rule63-overruled)
   (system no)
   (support-rule rule63-support)
   (defeasibly-rule rule63-defeasibly)
   (defeated-rule nil))

([rule64] of defeasible-rule
   (rule-name rule64)
   (original-rule "rule64 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"duznost_staranja\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"teska_tjelesna_povreda\" ) ) => ( crime_art156_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156_2)
   (negated no)
   (superior)
   (deductive-rule rule64-deductive)
   (overruled-rule rule64-overruled)
   (system no)
   (support-rule rule64-support)
   (defeasibly-rule rule64-defeasibly)
   (defeated-rule nil))

([rule65] of defeasible-rule
   (rule-name rule65)
   (original-rule "rule65 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"povjereno_nemocno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"smrt\" ) ) => ( crime_art156_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156_3)
   (negated no)
   (superior)
   (deductive-rule rule65-deductive)
   (overruled-rule rule65-overruled)
   (system no)
   (support-rule rule65-support)
   (defeasibly-rule rule65-defeasibly)
   (defeated-rule nil))

([rule66] of defeasible-rule
   (rule-name rule66)
   (original-rule "rule66 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"duznost_staranja\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"smrt\" ) ) => ( crime_art156_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156_3)
   (negated no)
   (superior)
   (deductive-rule rule66-deductive)
   (overruled-rule rule66-overruled)
   (system no)
   (support-rule rule66-support)
   (defeasibly-rule rule66-defeasibly)
   (defeated-rule nil))

([rule67] of defeasible-rule
   (rule-name rule67)
   (original-rule "rule67 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"prolaznik\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:help_provision_ability \"mogao_bez_opasnosti\" ) ) => ( crime_art157 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art157)
   (negated no)
   (superior)
   (deductive-rule rule67-deductive)
   (overruled-rule rule67-overruled)
   (system no)
   (support-rule rule67-support)
   (defeasibly-rule rule67-defeasibly)
   (defeated-rule nil))

([rule68] of defeasible-rule
   (rule-name rule68)
   (original-rule "rule68 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"prolaznik\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:help_provision_ability \"mogao_bez_opasnosti\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"teska_tjelesna_povreda\" ) ) => ( crime_art157_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art157_2)
   (negated no)
   (superior)
   (deductive-rule rule68-deductive)
   (overruled-rule rule68-overruled)
   (system no)
   (support-rule rule68-support)
   (defeasibly-rule rule68-defeasibly)
   (defeated-rule nil))

([rule69] of defeasible-rule
   (rule-name rule69)
   (original-rule "rule69 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"prolaznik\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:help_provision_ability \"mogao_bez_opasnosti\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:failure_to_help_consequence \"smrt\" ) ) => ( crime_art157_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art157_3)
   (negated no)
   (superior)
   (deductive-rule rule69-deductive)
   (overruled-rule rule69-overruled)
   (system no)
   (support-rule rule69-support)
   (defeasibly-rule rule69-defeasibly)
   (defeated-rule nil))

([rule70] of defeasible-rule
   (rule-name rule70)
   (original-rule "rule70 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetnik\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"bitno_smanjena_uracunljivost\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ) ( not ( and ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"punoljetno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_health_state \"tesko_zdravstveno_stanje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_explicit_request \"da\" ) ) ) ) => ( crime_art149_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_1)
   (negated no)
   (superior)
   (deductive-rule rule70-deductive)
   (overruled-rule rule70-overruled)
   (system no)
   (support-rule rule70-support)
   (defeasibly-rule rule70-defeasibly)
   (defeated-rule nil))

([rule71] of defeasible-rule
   (rule-name rule71)
   (original-rule "rule71 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"maloljetnik\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"bitno_smanjena_uracunljivost\" ) ) ) ( not ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ) ( not ( and ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"punoljetno_lice\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_health_state \"tesko_zdravstveno_stanje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_explicit_request \"da\" ) ) ) ) => ( crime_art149_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_1)
   (negated no)
   (superior)
   (deductive-rule rule71-deductive)
   (overruled-rule rule71-overruled)
   (system no)
   (support-rule rule71-support)
   (defeasibly-rule rule71-defeasibly)
   (defeated-rule nil))

([rule72] of defeasible-rule
   (rule-name rule72)
   (original-rule "rule72 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_4)
   (negated no)
   (superior)
   (deductive-rule rule72-deductive)
   (overruled-rule rule72-overruled)
   (system no)
   (support-rule rule72-support)
   (defeasibly-rule rule72-defeasibly)
   (defeated-rule nil))

([rule72b] of defeasible-rule
   (rule-name rule72b)
   (original-rule "rule72b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule72b-deductive)
   (overruled-rule rule72b-overruled)
   (system no)
   (support-rule rule72b-support)
   (defeasibly-rule rule72b-defeasibly)
   (defeated-rule nil))

([rule73] of defeasible-rule
   (rule-name rule73)
   (original-rule "rule73 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art149_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_4)
   (negated no)
   (superior)
   (deductive-rule rule73-deductive)
   (overruled-rule rule73-overruled)
   (system no)
   (support-rule rule73-support)
   (defeasibly-rule rule73-defeasibly)
   (defeated-rule nil))

([rule73b] of defeasible-rule
   (rule-name rule73b)
   (original-rule "rule73b ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_accountability \"neuracunljivo\" ) ) ( or ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule73b-deductive)
   (overruled-rule rule73b-overruled)
   (system no)
   (support-rule rule73b-support)
   (defeasibly-rule rule73b-defeasibly)
   (defeated-rule nil))

