([rule1] of defeasible-rule
   (rule-name rule1)
   (original-rule "rule1 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) => ( crime_art151_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_1)
   (negated no)
   (superior)
   (deductive-rule rule1-deductive)
   (overruled-rule rule1-overruled)
   (system no)
   (support-rule rule1-support)
   (defeasibly-rule rule1-defeasibly)
   (defeated-rule nil))

([rule2] of defeasible-rule
   (rule-name rule2)
   (original-rule "rule2 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon_used \"true\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule2-deductive)
   (overruled-rule rule2-overruled)
   (system no)
   (support-rule rule2-support)
   (defeasibly-rule rule2-defeasibly)
   (defeated-rule nil))

([rule3] of defeasible-rule
   (rule-name rule3)
   (original-rule "rule3 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_consequence \"true\" ) ) => ( crime_art151_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_3)
   (negated no)
   (superior)
   (deductive-rule rule3-deductive)
   (overruled-rule rule3-overruled)
   (system no)
   (support-rule rule3-support)
   (defeasibly-rule rule3-defeasibly)
   (defeated-rule nil))

([rule4] of defeasible-rule
   (rule-name rule4)
   (original-rule "rule4 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:death_result \"true\" ) ) => ( crime_art151_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_4)
   (negated no)
   (superior)
   (deductive-rule rule4-deductive)
   (overruled-rule rule4-overruled)
   (system no)
   (support-rule rule4-support)
   (defeasibly-rule rule4-defeasibly)
   (defeated-rule nil))

([rule5] of defeasible-rule
   (rule-name rule5)
   (original-rule "rule5 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:negligence \"true\" ) ) => ( crime_art151_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_5)
   (negated no)
   (superior)
   (deductive-rule rule5-deductive)
   (overruled-rule rule5-overruled)
   (system no)
   (support-rule rule5-support)
   (defeasibly-rule rule5-defeasibly)
   (defeated-rule nil))

([rule6] of defeasible-rule
   (rule-name rule6)
   (original-rule "rule6 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"laka tjelesna povreda\" ) ) => ( crime_art152_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_1)
   (negated no)
   (superior)
   (deductive-rule rule6-deductive)
   (overruled-rule rule6-overruled)
   (system no)
   (support-rule rule6-support)
   (defeasibly-rule rule6-defeasibly)
   (defeated-rule nil))

([rule7] of defeasible-rule
   (rule-name rule7)
   (original-rule "rule7 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"laka tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon_used \"true\" ) ) => ( crime_art152_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_2)
   (negated no)
   (superior)
   (deductive-rule rule7-deductive)
   (overruled-rule rule7-overruled)
   (system no)
   (support-rule rule7-support)
   (defeasibly-rule rule7-defeasibly)
   (defeated-rule nil))

([rule8] of defeasible-rule
   (rule-name rule8)
   (original-rule "rule8 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:provocation \"true\" ) ) => ( crime_art153 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art153)
   (negated no)
   (superior)
   (deductive-rule rule8-deductive)
   (overruled-rule rule8-overruled)
   (system no)
   (support-rule rule8-support)
   (defeasibly-rule rule8-defeasibly)
   (defeated-rule nil))

([rule9] of defeasible-rule
   (rule-name rule9)
   (original-rule "rule9 ( lc:case ( lc:defendant ?Defendant ) ( lc:fight_participation \"true\" ) ) => ( crime_art154 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art154)
   (negated no)
   (superior)
   (deductive-rule rule9-deductive)
   (overruled-rule rule9-overruled)
   (system no)
   (support-rule rule9-support)
   (defeasibly-rule rule9-defeasibly)
   (defeated-rule nil))

([rule10] of defeasible-rule
   (rule-name rule10)
   (original-rule "rule10 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) => ( crime_art155_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art155_1)
   (negated no)
   (superior)
   (deductive-rule rule10-deductive)
   (overruled-rule rule10-overruled)
   (system no)
   (support-rule rule10-support)
   (defeasibly-rule rule10-defeasibly)
   (defeated-rule nil))

([rule11] of defeasible-rule
   (rule-name rule11)
   (original-rule "rule11 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_direktni\" ) ) => ( crime_art143 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art143)
   (negated no)
   (superior)
   (deductive-rule rule11-deductive)
   (overruled-rule rule11-overruled)
   (system no)
   (support-rule rule11-support)
   (defeasibly-rule rule11-defeasibly)
   (defeated-rule nil))

([rule12] of defeasible-rule
   (rule-name rule12)
   (original-rule "rule12 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"umisljaj_eventualni\" ) ) => ( crime_art143 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art143)
   (negated no)
   (superior)
   (deductive-rule rule12-deductive)
   (overruled-rule rule12-overruled)
   (system no)
   (support-rule rule12-support)
   (defeasibly-rule rule12-defeasibly)
   (defeated-rule nil))

([rule13] of defeasible-rule
   (rule-name rule13)
   (original-rule "rule13 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"dijete\" ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule13-deductive)
   (overruled-rule rule13-overruled)
   (system no)
   (support-rule rule13-support)
   (defeasibly-rule rule13-defeasibly)
   (defeated-rule nil))

([rule14] of defeasible-rule
   (rule-name rule14)
   (original-rule "rule14 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_status \"bremenita_zena\" ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule14-deductive)
   (overruled-rule rule14-overruled)
   (system no)
   (support-rule rule14-support)
   (defeasibly-rule rule14-defeasibly)
   (defeated-rule nil))

([rule15] of defeasible-rule
   (rule-name rule15)
   (original-rule "rule15 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_to_third_parties \"true\" ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule15-deductive)
   (overruled-rule rule15-overruled)
   (system no)
   (support-rule rule15-support)
   (defeasibly-rule rule15-defeasibly)
   (defeated-rule nil))

([rule16] of defeasible-rule
   (rule-name rule16)
   (original-rule "rule16 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_count \"vise\" ) ) => ( crime_art144 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art144)
   (negated no)
   (superior)
   (deductive-rule rule16-deductive)
   (overruled-rule rule16-overruled)
   (system no)
   (support-rule rule16-support)
   (defeasibly-rule rule16-defeasibly)
   (defeated-rule nil))

([rule17] of defeasible-rule
   (rule-name rule17)
   (original-rule "rule17 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:execution_manner \"na_mah\" ) ) => ( crime_art145 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art145)
   (negated no)
   (superior)
   (deductive-rule rule17-deductive)
   (overruled-rule rule17-overruled)
   (system no)
   (support-rule rule17-support)
   (defeasibly-rule rule17-defeasibly)
   (defeated-rule nil))

([rule18] of defeasible-rule
   (rule-name rule18)
   (original-rule "rule18 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_psych_state \"jaka_razdrazenost_na_mah\" ) ) => ( crime_art145 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art145)
   (negated no)
   (superior)
   (deductive-rule rule18-deductive)
   (overruled-rule rule18-overruled)
   (system no)
   (support-rule rule18-support)
   (defeasibly-rule rule18-defeasibly)
   (defeated-rule nil))

([rule19] of defeasible-rule
   (rule-name rule19)
   (original-rule "rule19 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_psych_state \"porodjajni_poremecaj\" ) ) => ( crime_art146 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art146)
   (negated no)
   (superior)
   (deductive-rule rule19-deductive)
   (overruled-rule rule19-overruled)
   (system no)
   (support-rule rule19-support)
   (defeasibly-rule rule19-defeasibly)
   (defeated-rule nil))

([rule20] of defeasible-rule
   (rule-name rule20)
   (original-rule "rule20 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_explicit_request \"da\" ) ) => ( crime_art147 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art147)
   (negated no)
   (superior)
   (deductive-rule rule20-deductive)
   (overruled-rule rule20-overruled)
   (system no)
   (support-rule rule20-support)
   (defeasibly-rule rule20-defeasibly)
   (defeated-rule nil))

([rule21] of defeasible-rule
   (rule-name rule21)
   (original-rule "rule21 ( lc:case ( lc:defendant ?Defendant ) ( lc:life_consequence_type \"smrt_nastupila\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:guilt_form \"nehat\" ) ) => ( crime_art148 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art148)
   (negated no)
   (superior)
   (deductive-rule rule21-deductive)
   (overruled-rule rule21-overruled)
   (system no)
   (support-rule rule21-support)
   (defeasibly-rule rule21-defeasibly)
   (defeated-rule nil))

([rule22] of defeasible-rule
   (rule-name rule22)
   (original-rule "rule22 ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"navodjenje_na_samoubistvo\" ) ) => ( crime_art149_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_1)
   (negated no)
   (superior)
   (deductive-rule rule22-deductive)
   (overruled-rule rule22-overruled)
   (system no)
   (support-rule rule22-support)
   (defeasibly-rule rule22-defeasibly)
   (defeated-rule nil))

([rule23] of defeasible-rule
   (rule-name rule23)
   (original-rule "rule23 ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"izvrseno\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"pomaganje_u_samoubistvu\" ) ) => ( crime_art149_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_2)
   (negated no)
   (superior)
   (deductive-rule rule23-deductive)
   (overruled-rule rule23-overruled)
   (system no)
   (support-rule rule23-support)
   (defeasibly-rule rule23-defeasibly)
   (defeated-rule nil))

([rule24] of defeasible-rule
   (rule-name rule24)
   (original-rule "rule24 ( lc:case ( lc:defendant ?Defendant ) ( lc:suicide_outcome \"pokusano\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:inhuman_treatment \"true\" ) ) => ( crime_art149_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art149_5)
   (negated no)
   (superior)
   (deductive-rule rule24-deductive)
   (overruled-rule rule24-overruled)
   (system no)
   (support-rule rule24-support)
   (defeasibly-rule rule24-defeasibly)
   (defeated-rule nil))

([rule25] of defeasible-rule
   (rule-name rule25)
   (original-rule "rule25 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"nelegalni_pobacaj\" ) ) => ( crime_art150 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150)
   (negated no)
   (superior)
   (deductive-rule rule25-deductive)
   (overruled-rule rule25-overruled)
   (system no)
   (support-rule rule25-support)
   (defeasibly-rule rule25-defeasibly)
   (defeated-rule nil))

([rule26] of defeasible-rule
   (rule-name rule26)
   (original-rule "rule26 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"sakacenje_zenskih_genitalija\" ) ) => ( crime_art151a ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151a)
   (negated no)
   (superior)
   (deductive-rule rule26-deductive)
   (overruled-rule rule26-overruled)
   (system no)
   (support-rule rule26-support)
   (defeasibly-rule rule26-defeasibly)
   (defeated-rule nil))

([rule27] of defeasible-rule
   (rule-name rule27)
   (original-rule "rule27 ( lc:case ( lc:defendant ?Defendant ) ( lc:special_action_types \"prisilna_sterilizacija\" ) ) => ( crime_art151b ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151b)
   (negated no)
   (superior)
   (deductive-rule rule27-deductive)
   (overruled-rule rule27-overruled)
   (system no)
   (support-rule rule27-support)
   (defeasibly-rule rule27-defeasibly)
   (defeated-rule nil))

([rule28] of defeasible-rule
   (rule-name rule28)
   (original-rule "rule28 ( lc:case ( lc:defendant ?Defendant ) ( lc:sterilization_goal \"onemogucavanje_reprodukcije\" ) ) => ( crime_art151b ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151b)
   (negated no)
   (superior)
   (deductive-rule rule28-deductive)
   (overruled-rule rule28-overruled)
   (system no)
   (support-rule rule28-support)
   (defeasibly-rule rule28-defeasibly)
   (defeated-rule nil))

([rule29] of defeasible-rule
   (rule-name rule29)
   (original-rule "rule29 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"povjereno_nemocno_lice\" ) ) => ( crime_art156 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156)
   (negated no)
   (superior)
   (deductive-rule rule29-deductive)
   (overruled-rule rule29-overruled)
   (system no)
   (support-rule rule29-support)
   (defeasibly-rule rule29-defeasibly)
   (defeated-rule nil))

([rule30] of defeasible-rule
   (rule-name rule30)
   (original-rule "rule30 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"duznost_staranja\" ) ) => ( crime_art156 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art156)
   (negated no)
   (superior)
   (deductive-rule rule30-deductive)
   (overruled-rule rule30-overruled)
   (system no)
   (support-rule rule30-support)
   (defeasibly-rule rule30-defeasibly)
   (defeated-rule nil))

([rule31] of defeasible-rule
   (rule-name rule31)
   (original-rule "rule31 ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:offender_victim_relationship \"prolaznik\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:help_provision_ability \"mogao_bez_opasnosti\" ) ) => ( crime_art157 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art157)
   (negated no)
   (superior)
   (deductive-rule rule31-deductive)
   (overruled-rule rule31-overruled)
   (system no)
   (support-rule rule31-support)
   (defeasibly-rule rule31-defeasibly)
   (defeated-rule nil))

([rule32] of defeasible-rule
   (rule-name rule32)
   (original-rule "rule32 ( lc:case ( lc:defendant ?Defendant ) ( lc:abortion_outcomes \"pobacaj_izvrsen\" ) ) => ( crime_art150 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art150)
   (negated no)
   (superior)
   (deductive-rule rule32-deductive)
   (overruled-rule rule32-overruled)
   (system no)
   (support-rule rule32-support)
   (defeasibly-rule rule32-defeasibly)
   (defeated-rule nil))

([rule33] of defeasible-rule
   (rule-name rule33)
   (original-rule "rule33 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_means_type \"opasno_orudje\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity_level \"laka\" ) ) => ( crime_art152_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_2)
   (negated no)
   (superior)
   (deductive-rule rule33-deductive)
   (overruled-rule rule33-overruled)
   (system no)
   (support-rule rule33-support)
   (defeasibly-rule rule33-defeasibly)
   (defeated-rule nil))

([rule34] of defeasible-rule
   (rule-name rule34)
   (original-rule "rule34 ( lc:case ( lc:defendant ?Defendant ) ( lc:danger_caused_by_offender \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:left_without_help \"true\" ) ) => ( crime_art155_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art155_1)
   (negated no)
   (superior)
   (deductive-rule rule34-deductive)
   (overruled-rule rule34-overruled)
   (system no)
   (support-rule rule34-support)
   (defeasibly-rule rule34-defeasibly)
   (defeated-rule nil))

