([crime_art151_1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art151_1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art151_1)
   (rules [rule1])
   (defeasible-stratum 0))

([crime_art151_2] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art151_2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art151_2)
   (rules [rule2])
   (defeasible-stratum 0))

([crime_art151_3] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art151_3)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art151_3)
   (rules [rule3])
   (defeasible-stratum 0))

([crime_art151_4] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art151_4)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art151_4)
   (rules [rule4])
   (defeasible-stratum 0))

([crime_art151_5] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art151_5)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art151_5)
   (rules [rule5])
   (defeasible-stratum 0))

([crime_art152_1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art152_1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art152_1)
   (rules [rule6])
   (defeasible-stratum 0))

([crime_art152_2] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art152_2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art152_2)
   (rules [rule33] [rule7])
   (defeasible-stratum 0))

([crime_art153] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art153)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art153)
   (rules [rule8])
   (defeasible-stratum 0))

([crime_art154] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art154)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art154)
   (rules [rule9])
   (defeasible-stratum 0))

([crime_art155_1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art155_1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art155_1)
   (rules [rule34] [rule10])
   (defeasible-stratum 0))

([crime_art143] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art143)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art143)
   (rules [rule12] [rule11])
   (defeasible-stratum 0))

([crime_art144] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art144)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art144)
   (rules [rule16] [rule15] [rule14] [rule13])
   (defeasible-stratum 0))

([crime_art145] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art145)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art145)
   (rules [rule18] [rule17])
   (defeasible-stratum 0))

([crime_art146] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art146)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art146)
   (rules [rule19])
   (defeasible-stratum 0))

([crime_art147] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art147)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art147)
   (rules [rule20])
   (defeasible-stratum 0))

([crime_art148] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art148)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art148)
   (rules [rule21])
   (defeasible-stratum 0))

([crime_art149_1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art149_1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art149_1)
   (rules [rule22])
   (defeasible-stratum 0))

([crime_art149_2] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art149_2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art149_2)
   (rules [rule23])
   (defeasible-stratum 0))

([crime_art149_5] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art149_5)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art149_5)
   (rules [rule24])
   (defeasible-stratum 0))

([crime_art150] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art150)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art150)
   (rules [rule32] [rule25])
   (defeasible-stratum 0))

([crime_art151a] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art151a)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art151a)
   (rules [rule26])
   (defeasible-stratum 0))

([crime_art151b] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art151b)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art151b)
   (rules [rule28] [rule27])
   (defeasible-stratum 0))

([crime_art156] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art156)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art156)
   (rules [rule30] [rule29])
   (defeasible-stratum 0))

([crime_art157] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label crime_art157)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name crime_art157)
   (rules [rule31])
   (defeasible-stratum 0))

