([rule1] of defeasible-rule
   (rule-name rule1)
   (original-rule "rule1 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) => ( crime_art151_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_1)
   (negated no)
   (superior)
   (deductive-rule rule1-deductive)
   (overruled-rule rule1-overruled)
   (system no)
   (support-rule rule1-support)
   (defeasibly-rule rule1-defeasibly)
   (defeated-rule nil))

([rule2] of defeasible-rule
   (rule-name rule2)
   (original-rule "rule2 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon \"metalni kljuc\" ) ) => ( crime_art151_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_2)
   (negated no)
   (superior)
   (deductive-rule rule2-deductive)
   (overruled-rule rule2-overruled)
   (system no)
   (support-rule rule2-support)
   (defeasibly-rule rule2-defeasibly)
   (defeated-rule nil))

([rule3] of defeasible-rule
   (rule-name rule3)
   (original-rule "rule3 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon \"staklena flasa\" ) ) => ( crime_art151_3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_3)
   (negated no)
   (superior)
   (deductive-rule rule3-deductive)
   (overruled-rule rule3-overruled)
   (system no)
   (support-rule rule3-support)
   (defeasibly-rule rule3-defeasibly)
   (defeated-rule nil))

([rule4] of defeasible-rule
   (rule-name rule4)
   (original-rule "rule4 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:location \"Podgorica\" ) ) => ( crime_art151_4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_4)
   (negated no)
   (superior)
   (deductive-rule rule4-deductive)
   (overruled-rule rule4-overruled)
   (system no)
   (support-rule rule4-support)
   (defeasibly-rule rule4-defeasibly)
   (defeated-rule nil))

([rule5] of defeasible-rule
   (rule-name rule5)
   (original-rule "rule5 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:location \"Skadar\" ) ) => ( crime_art151_5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art151_5)
   (negated no)
   (superior)
   (deductive-rule rule5-deductive)
   (overruled-rule rule5-overruled)
   (system no)
   (support-rule rule5-support)
   (defeasibly-rule rule5-defeasibly)
   (defeated-rule nil))

([rule6] of defeasible-rule
   (rule-name rule6)
   (original-rule "rule6 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"laka tjelesna povreda\" ) ) => ( crime_art152_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_1)
   (negated no)
   (superior)
   (deductive-rule rule6-deductive)
   (overruled-rule rule6-overruled)
   (system no)
   (support-rule rule6-support)
   (defeasibly-rule rule6-defeasibly)
   (defeated-rule nil))

([rule7] of defeasible-rule
   (rule-name rule7)
   (original-rule "rule7 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"laka tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:weapon \"metalni kljuc\" ) ) => ( crime_art152_2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art152_2)
   (negated no)
   (superior)
   (deductive-rule rule7-deductive)
   (overruled-rule rule7-overruled)
   (system no)
   (support-rule rule7-support)
   (defeasibly-rule rule7-defeasibly)
   (defeated-rule nil))

([rule8] of defeasible-rule
   (rule-name rule8)
   (original-rule "rule8 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:location \"Danilovgrad\" ) ) => ( crime_art153 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art153)
   (negated no)
   (superior)
   (deductive-rule rule8-deductive)
   (overruled-rule rule8-overruled)
   (system no)
   (support-rule rule8-support)
   (defeasibly-rule rule8-defeasibly)
   (defeated-rule nil))

([rule9] of defeasible-rule
   (rule-name rule9)
   (original-rule "rule9 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:location \"Podgorici Kv\" ) ) => ( crime_art154 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art154)
   (negated no)
   (superior)
   (deductive-rule rule9-deductive)
   (overruled-rule rule9-overruled)
   (system no)
   (support-rule rule9-support)
   (defeasibly-rule rule9-defeasibly)
   (defeated-rule nil))

([rule10] of defeasible-rule
   (rule-name rule10)
   (original-rule "rule10 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_type \"teska tjelesna povreda\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:location \"Sto\" ) ) => ( crime_art155_1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class crime_art155_1)
   (negated no)
   (superior)
   (deductive-rule rule10-deductive)
   (overruled-rule rule10-overruled)
   (system no)
   (support-rule rule10-support)
   (defeasibly-rule rule10-defeasibly)
   (defeated-rule nil))

